### ISSUE TITLE
Incompatible with DataGrip 2021.3

### ISSUE THREAD

**Issue by tomashm** [scrappyCoco/Painless-Transact-SQL#1]
Plugin error: Plugin 'Painless Transact SQL' (version '2020.2.2') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is DB-211.6693.68

**Comment by scrappyCoco** [comment]
@tomashm, thanks for your comment. I will fix it in the nearest days.

**Comment by scrappyCoco** [comment]
@tomashm, the plugin has been updated. You can try to update it.

**Comment by tomashm** [comment]
Thanks, it works now :)
